scanner:
    linter: flake8  # Other option is pycodestyle

no_blank_comment: False  # If True, no comment is made on PR without any errors.
descending_issues_order: True  # If True, PEP 8 issues in message will be displayed in descending order of line numbers in the file

[flake8]
filename = 
    *.rc,

exclude =
    .git,
    .github,

ignore =
    E265,
    E266,
    F821,
    W504,

max-line-length = 85
