name: repo-tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]


jobs:
  gitchangelog_test:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    name: Test changelog
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        if: matrix.os == 'ubuntu-20.04'
        id: get_version
        run: |
          echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
          echo ${{ env.VERSION }}

      - name: gitchangelog action step (debug)
        uses: ./ # Uses an action in the root directory
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}

      - name: Display changes file
        run: cat CHANGES.md

      - name: Checkout test repo
        uses: actions/checkout@v2
        with:
          repository: sarnold/gitchangelog
          path: vendor/gcl-test

      - name: Display subdir result
        run: ls -l vendor/
